import { DumpError, lastResult, qualifyTable, quoteIdent, quoteLiteral, type EngineApi } from "@workbench/shared"
import { Effect } from "effect"

export const bytesToBase64 = (bytes: Uint8Array): string => {
  let binary = ""
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return btoa(binary)
}

export const base64ToBytes = (value: string): Uint8Array => {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

export const DUMP_SQL_MAX_ROWS = 50_000

export const dumpSqlFromEngine = (engine: EngineApi, maxRows = DUMP_SQL_MAX_ROWS) =>
  Effect.gen(function* () {
    const catalog = yield* engine.introspect.pipe(
      Effect.mapError((e) => new DumpError({ message: e.message }))
    )
    const parts: Array<string> = [`-- dump generated by wasm sql workbench (${engine.engine})`]
    for (const table of catalog.tables.filter((t) => t.kind === "table")) {
      const colDefs = table.columns
        .map((c) => {
          const bits = [`${quoteIdent(engine.dialect, c.name)} ${c.type || "TEXT"}`]
          if (!c.nullable) bits.push("NOT NULL")
          return bits.join(" ")
        })
        .join(", ")
      const pks = table.columns.filter((c) => c.pk).map((c) => quoteIdent(engine.dialect, c.name))
      const pk = pks.length > 0 ? `, PRIMARY KEY (${pks.join(", ")})` : ""
      const qtable = qualifyTable(engine.dialect, table.schema, table.name)
      parts.push(`CREATE TABLE IF NOT EXISTS ${qtable} (${colDefs}${pk});`)
      const data = lastResult(
        yield* engine
          .query(`SELECT * FROM ${qtable} LIMIT ${maxRows}`)
          .pipe(Effect.mapError((e) => new DumpError({ message: e.message })))
      )
      for (const row of data.rows) {
        const cols = data.columns.map((c) => quoteIdent(engine.dialect, c)).join(", ")
        const values = row.map((v) => quoteLiteral(v)).join(", ")
        parts.push(`INSERT INTO ${qtable} (${cols}) VALUES (${values});`)
      }
      if (data.rowCount >= maxRows) {
        parts.push(`-- truncated ${qtable} at ${maxRows} rows; use binary export for full dump`)
      }
    }
    return parts.join("\n")
  })

export const downloadText = (filename: string, contents: string, type = "text/plain") => {
  const blob = new Blob([contents], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const downloadBytes = (filename: string, bytes: Uint8Array) => {
  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: "application/octet-stream" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const toCsv = (columns: Array<string>, rows: Array<Array<unknown>>): string => {
  const cell = (v: unknown) => {
    const s = v === null || v === undefined ? "" : String(v)
    return /[",\n]/.test(s) ? `"${s.replaceAll("\"", "\"\"")}"` : s
  }
  return [columns.map(cell).join(","), ...rows.map((r) => r.map(cell).join(","))].join("\n")
}
