import {
  DumpError,
  lastResult,
  qualifyTable,
  quoteIdent,
  quoteLiteral,
  type EngineApi,
  type Table
} from "@workbench/shared"
import { Effect } from "effect"

export const bytesToBase64 = (bytes: Uint8Array): string => {
  let binary = ""
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return btoa(binary)
}

export const base64ToBytes = (value: string): Uint8Array => {
  const binary = atob(value)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

export const DUMP_SQL_MAX_ROWS = 50_000

/** Reconstruct CREATE TABLE / approximate DDL from catalog metadata. */
export const tableCreateSql = (dialect: "pgsql" | "sqlite", table: Table): string => {
  const qtable = qualifyTable(dialect, table.schema, table.name)
  if (table.kind === "view") {
    return `-- View ${qtable}\n-- Definition not stored in catalog; open sqlite_master / pg_get_viewdef for source.`
  }
  const colDefs = table.columns
    .map((c) => {
      const bits = [`${quoteIdent(dialect, c.name)} ${c.type || "TEXT"}`]
      if (!c.nullable) bits.push("NOT NULL")
      return bits.join(" ")
    })
    .join(",\n  ")
  const pks = table.columns.filter((c) => c.pk).map((c) => quoteIdent(dialect, c.name))
  const pk = pks.length > 0 ? `,\n  PRIMARY KEY (${pks.join(", ")})` : ""
  const fks = table.columns
    .filter((c) => c.fkTable && c.fkColumn)
    .map(
      (c) =>
        `,\n  FOREIGN KEY (${quoteIdent(dialect, c.name)}) REFERENCES ${quoteIdent(dialect, c.fkTable!)} (${quoteIdent(dialect, c.fkColumn!)})`
    )
    .join("")
  return `CREATE TABLE ${qtable} (\n  ${colDefs}${pk}${fks}\n);`
}

/** Prefer engine-native DDL when available (SQLite sqlite_master / Postgres pg_get_viewdef). */
export const fetchTableDdl = (engine: EngineApi, table: Table) =>
  Effect.gen(function* () {
    if (engine.dialect === "sqlite") {
      const res = yield* engine.query(
        `SELECT sql FROM sqlite_master WHERE name = ${quoteLiteral(table.name)} AND type IN ('table','view') LIMIT 1`
      )
      const sql = lastResult(res).rows[0]?.[0]
      if (typeof sql === "string" && sql.trim()) return sql.endsWith(";") ? sql : `${sql};`
    }
    if (engine.dialect === "pgsql" && table.kind === "view") {
      const res = yield* engine.query(
        `SELECT pg_get_viewdef(${quoteLiteral(`${table.schema}.${table.name}`)}::regclass, true)`
      )
      const def = lastResult(res).rows[0]?.[0]
      if (typeof def === "string" && def.trim()) {
        const qtable = qualifyTable(engine.dialect, table.schema, table.name)
        return `CREATE OR REPLACE VIEW ${qtable} AS\n${def.endsWith(";") ? def : `${def};`}`
      }
    }
    return tableCreateSql(engine.dialect, table)
  }).pipe(Effect.catchAll(() => Effect.succeed(tableCreateSql(engine.dialect, table))))

export const dumpSqlFromEngine = (engine: EngineApi, maxRows = DUMP_SQL_MAX_ROWS) =>
  Effect.gen(function* () {
    const catalog = yield* engine.introspect.pipe(
      Effect.mapError((e) => new DumpError({ message: e.message }))
    )
    const parts: Array<string> = [`-- dump generated by wasm sql workbench (${engine.engine})`]
    for (const table of catalog.tables.filter((t) => t.kind === "table")) {
      parts.push(tableCreateSql(engine.dialect, table))
      const qtable = qualifyTable(engine.dialect, table.schema, table.name)
      const data = lastResult(
        yield* engine
          .query(`SELECT * FROM ${qtable} LIMIT ${maxRows}`)
          .pipe(Effect.mapError((e) => new DumpError({ message: e.message })))
      )
      for (const row of data.rows) {
        const cols = data.columns.map((c) => quoteIdent(engine.dialect, c)).join(", ")
        const values = row.map((v) => quoteLiteral(v)).join(", ")
        parts.push(`INSERT INTO ${qtable} (${cols}) VALUES (${values});`)
      }
      if (data.rowCount >= maxRows) {
        parts.push(`-- truncated ${qtable} at ${maxRows} rows; use binary export for full dump`)
      }
    }
    return parts.join("\n")
  })

export const downloadText = (filename: string, contents: string, type = "text/plain") => {
  const blob = new Blob([contents], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const downloadBytes = (filename: string, bytes: Uint8Array) => {
  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: "application/octet-stream" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export const toCsv = (columns: Array<string>, rows: Array<Array<unknown>>): string => {
  const cell = (v: unknown) => {
    const s = v === null || v === undefined ? "" : String(v)
    return /[",\n]/.test(s) ? `"${s.replaceAll("\"", "\"\"")}"` : s
  }
  return [columns.map(cell).join(","), ...rows.map((r) => r.map(cell).join(","))].join("\n")
}
